use crate::analysis::CommandAnalyzer;
use crate::generators::base::file_writer::FileWriter;
use crate::generators::base::template_context::{CommandContext, EventContext, FieldContext};
use crate::generators::base::templates::GlobalContext;
use crate::generators::base::type_conversion::TypeConverter;
use crate::generators::base::type_visitor::{TypeScriptVisitor, ZodVisitor};
use crate::generators::base::{BaseBindingsGenerator, BaseGenerator};
use crate::models::{CommandInfo, EventInfo, StructInfo};
use std::collections::{HashMap, HashSet};
use tera::{Context, Tera};

/// Generator for Zod schema-based TypeScript bindings with validation
pub struct ZodBindingsGenerator {
    base: BaseGenerator,
    type_converter: TypeConverter,
    tera: Tera,
}

impl ZodBindingsGenerator {
    pub fn new() -> Self {
        Self {
            base: BaseGenerator::new(),
            type_converter: TypeConverter::new(),
            tera: super::templates::create_template_engine()
                .expect("Failed to initialize Zod template engine"),
        }
    }

    /// Generate file header using templates
    fn generate_file_header(&self) -> String {
        let global_context = GlobalContext::new("zod");
        let mut context = Context::new();
        context.insert("global", &global_context);

        super::templates::render(&self.tera, "common/header.tera", &context)
            .unwrap_or_else(|e| {
                eprintln!("Failed to render header template: {}", e);
                // Fallback to simple header
                let version = env!("CARGO_PKG_VERSION");
                let timestamp = chrono::Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Secs, true);
                format!(
                    "/**\n * Auto-generated TypeScript types for Tauri commands\n * Generated by tauri-typegen v{}\n * Generated at: {}\n * Do not edit manually - regenerate using: cargo tauri-typegen generate\n */\n\n",
                    version, timestamp
                )
            })
    }

    /// Generate Zod schema for a struct
    fn generate_struct_schema(&self, name: &str, struct_info: &StructInfo) -> String {
        if struct_info.is_enum {
            self.generate_enum_schema(name, struct_info)
        } else {
            self.generate_object_schema(name, struct_info)
        }
    }

    /// Generate Zod schema for an enum
    fn generate_enum_schema(&self, name: &str, struct_info: &StructInfo) -> String {
        let variants: Vec<String> = struct_info
            .fields
            .iter()
            .map(|field| format!("\"{}\"", field.serialized_name))
            .collect();

        let enum_values = variants.join(", ");
        format!(
            "export const {}Schema = z.enum([{}]);\n\n",
            name, enum_values
        )
    }

    /// Generate Zod schema for an object/struct using templates
    fn generate_object_schema(&self, name: &str, struct_info: &StructInfo) -> String {
        let visitor = ZodVisitor;

        // Convert FieldInfo to FieldContext with computed Zod schemas
        let field_contexts: Vec<FieldContext> = struct_info
            .fields
            .iter()
            .map(|field| FieldContext::from_field_info(field, &visitor))
            .collect();

        let mut context = Context::new();
        context.insert("name", name);
        context.insert("fields", &field_contexts);

        super::templates::render(&self.tera, "zod/partials/schema.ts.tera", &context)
            .unwrap_or_else(|e| {
                eprintln!("Template rendering failed for {}: {}", name, e);
                format!("// Error generating schema for {}: {}\n", name, e)
            })
    }

    /// Generate the complete types.ts file content (with embedded schemas)
    fn generate_types_file_content(
        &self,
        commands: &[CommandInfo],
        used_structs: &HashMap<String, StructInfo>,
        analyzer: &CommandAnalyzer,
    ) -> String {
        // Sort structs topologically
        let type_names: HashSet<String> = used_structs.keys().cloned().collect();
        let sorted_types = analyzer.topological_sort_types(&type_names);

        // Generate struct schemas
        let mut struct_schemas = String::new();
        for name in &sorted_types {
            if let Some(struct_info) = used_structs.get(name) {
                struct_schemas.push_str(&self.generate_struct_schema(name, struct_info));
            }
        }

        // Convert commands to context wrappers
        let visitor = ZodVisitor;
        let type_resolver = analyzer.get_type_resolver();
        let command_contexts: Vec<CommandContext> = commands
            .iter()
            .map(|cmd| {
                CommandContext::from_command_info(cmd, &visitor, &|rust_type: &str| {
                    type_resolver.borrow_mut().parse_type_structure(rust_type)
                })
            })
            .collect();

        // Generate parameter schemas using template
        let param_schemas = {
            let mut context = Context::new();
            context.insert("commands", &command_contexts);
            super::templates::render(&self.tera, "zod/partials/param_schemas.ts.tera", &context)
                .unwrap_or_else(|e| {
                    eprintln!("Template rendering failed for param schemas: {}", e);
                    String::new()
                })
        };

        // Generate type aliases using template
        let type_aliases = {
            let mut context = Context::new();
            context.insert("commands", &command_contexts);
            context.insert("struct_names", &sorted_types);
            super::templates::render(&self.tera, "zod/partials/type_aliases.ts.tera", &context)
                .unwrap_or_else(|e| {
                    eprintln!("Template rendering failed for type aliases: {}", e);
                    String::new()
                })
        };

        // Render main types.ts template
        let mut context = Context::new();
        context.insert("header", &self.generate_file_header());
        context.insert(
            "has_channels",
            &commands.iter().any(|cmd| !cmd.channels.is_empty()),
        );
        context.insert("struct_schemas", &struct_schemas);
        context.insert("param_schemas", &param_schemas);
        context.insert("type_aliases", &type_aliases);

        super::templates::render(&self.tera, "zod/types.ts.tera", &context).unwrap_or_else(|e| {
            eprintln!("Template rendering failed for types.ts: {}", e);
            String::new()
        })
    }

    /// Generate command bindings with validation
    fn generate_command_bindings(
        &self,
        commands: &[CommandInfo],
        analyzer: &CommandAnalyzer,
    ) -> String {
        // Use TypeScriptVisitor for command bindings to get proper TS types
        // (not Zod schemas) in function signatures
        let visitor = TypeScriptVisitor;
        let type_resolver = analyzer.get_type_resolver();

        // Convert commands to context wrappers
        let command_contexts: Vec<CommandContext> = commands
            .iter()
            .map(|cmd| {
                CommandContext::from_command_info(cmd, &visitor, &|rust_type: &str| {
                    type_resolver.borrow_mut().parse_type_structure(rust_type)
                })
            })
            .collect();

        let mut context = Context::new();
        context.insert("header", &self.generate_file_header());
        context.insert("commands", &command_contexts);
        context.insert(
            "has_channels",
            &commands.iter().any(|cmd| !cmd.channels.is_empty()),
        );

        super::templates::render(&self.tera, "zod/commands.ts.tera", &context).unwrap_or_else(|e| {
            eprintln!("Template rendering failed for commands.ts: {}", e);
            String::new()
        })
    }

    /// Generate index.ts file
    fn generate_index_file(&self, generated_files: &[String]) -> String {
        let mut context = Context::new();
        context.insert("header", &self.generate_file_header());
        context.insert("files", generated_files);

        super::templates::render(&self.tera, "zod/index.ts.tera", &context).unwrap_or_else(|e| {
            eprintln!("Template rendering failed for index.ts: {}", e);
            String::new()
        })
    }

    pub fn collect_referenced_types(&self, rust_type: &str, used_types: &mut HashSet<String>) {
        self.type_converter
            .collect_referenced_types(rust_type, used_types);
    }

    pub fn is_custom_type(&self, type_name: &str) -> bool {
        self.type_converter.is_custom_type(type_name)
    }

    /// Generate events file content
    fn generate_events_file(&self, events: &[EventInfo], analyzer: &CommandAnalyzer) -> String {
        let visitor = ZodVisitor;
        let type_resolver = analyzer.get_type_resolver();

        // Convert events to context wrappers
        let event_contexts: Vec<EventContext> = events
            .iter()
            .map(|event| {
                EventContext::from_event_info(event, &visitor, &|rust_type: &str| {
                    type_resolver.borrow_mut().parse_type_structure(rust_type)
                })
            })
            .collect();

        let mut context = Context::new();
        context.insert("header", &self.generate_file_header());
        context.insert("events", &event_contexts);

        super::templates::render(&self.tera, "zod/events.ts.tera", &context).unwrap_or_else(|e| {
            eprintln!("Template rendering failed for events.ts: {}", e);
            String::new()
        })
    }
}

impl BaseBindingsGenerator for ZodBindingsGenerator {
    fn generate_models(
        &mut self,
        commands: &[CommandInfo],
        discovered_structs: &HashMap<String, StructInfo>,
        output_path: &str,
        analyzer: &CommandAnalyzer,
    ) -> Result<Vec<String>, Box<dyn std::error::Error>> {
        // Set up the type converter with known structs
        self.type_converter
            .set_known_types(discovered_structs.clone());

        // Store known structs for reference
        self.base.known_structs = discovered_structs.clone();

        // Filter to only the types used by commands
        let mut used_structs = self.base.collect_used_types(commands, discovered_structs);

        // Also collect types used in events
        let events = analyzer.get_discovered_events();
        for event in events {
            let mut event_types = std::collections::HashSet::new();
            self.base
                .collect_referenced_types(&event.payload_type, &mut event_types);

            // Add event payload types to used_structs
            for type_name in event_types {
                if let Some(struct_info) = discovered_structs.get(&type_name) {
                    used_structs.insert(type_name.clone(), struct_info.clone());
                }
            }
        }

        // Create file writer
        let mut file_writer = FileWriter::new(output_path)?;

        // Generate and write types file (with embedded schemas)
        let types_content = self.generate_types_file_content(commands, &used_structs, analyzer);
        file_writer.write_types_file(&types_content)?;

        // Generate and write commands file
        let commands_content = self.generate_command_bindings(commands, analyzer);
        file_writer.write_commands_file(&commands_content)?;

        // Generate and write events file if there are any events
        let events = analyzer.get_discovered_events();
        if !events.is_empty() {
            let events_content = self.generate_events_file(events, analyzer);
            file_writer.write_events_file(&events_content)?;
        }

        // Generate and write index file
        let index_content = self.generate_index_file(file_writer.get_generated_files());
        file_writer.write_index_file(&index_content)?;

        Ok(file_writer.get_generated_files().to_vec())
    }
}

impl Default for ZodBindingsGenerator {
    fn default() -> Self {
        Self::new()
    }
}
