use crate::analysis::CommandAnalyzer;
use crate::models::{CommandInfo, StructInfo, ValidatorAttributes, LengthConstraint, RangeConstraint};
use std::collections::{HashMap, HashSet};
use std::fs;

/// Generator for Zod-based TypeScript bindings with validation
pub struct ZodGenerator {
    custom_types: HashSet<String>,
    known_structs: HashMap<String, StructInfo>,
}

impl ZodGenerator {
    pub fn new() -> Self {
        Self {
            custom_types: HashSet::new(),
            known_structs: HashMap::new(),
        }
    }

    pub fn generate_models(
        &mut self,
        commands: &[CommandInfo],
        discovered_structs: &HashMap<String, StructInfo>,
        output_path: &str,
        analyzer: &CommandAnalyzer,
    ) -> Result<Vec<String>, Box<dyn std::error::Error>> {
        let mut generated_files = Vec::new();

        // Store known structs for schema generation
        self.known_structs = discovered_structs.clone();

        // Collect all custom types
        self.collect_custom_types(commands);

        // Generate types file (with schemas and inferred types combined)
        let types_content = self.generate_types_file(commands, discovered_structs, analyzer)?;
        let types_file_path = format!("{}/types.ts", output_path);
        fs::create_dir_all(output_path)?;
        fs::write(&types_file_path, types_content)?;
        generated_files.push("types.ts".to_string());

        // Generate command bindings
        let bindings_content = self.generate_command_bindings(commands)?;
        let bindings_file_path = format!("{}/commands.ts", output_path);
        fs::write(&bindings_file_path, bindings_content)?;
        generated_files.push("commands.ts".to_string());

        // Generate index file
        let index_content = self.generate_index_file(&generated_files)?;
        let index_file_path = format!("{}/index.ts", output_path);
        fs::write(&index_file_path, index_content)?;
        generated_files.push("index.ts".to_string());

        Ok(generated_files)
    }

    fn collect_custom_types(&mut self, commands: &[CommandInfo]) {
        for command in commands {
            // Collect types from parameters
            for param in &command.parameters {
                if self.is_custom_type(&param.typescript_type) {
                    self.custom_types.insert(param.typescript_type.clone());
                }
            }

            // Collect type from return type
            if self.is_custom_type(&command.return_type) {
                self.custom_types.insert(command.return_type.clone());
            }
        }
    }

    fn generate_schemas_file(
        &self,
        commands: &[CommandInfo],
        discovered_structs: &HashMap<String, StructInfo>,
        analyzer: &CommandAnalyzer,
    ) -> Result<String, Box<dyn std::error::Error>> {
        let mut content = String::new();

        content.push_str(&format!(
            "/**\n * Auto-generated Zod schemas for Tauri commands\n * Generated by tauri-plugin-typegen\n * Do not edit manually - regenerate using: cargo tauri-typegen generate\n */\n\n"
        ));

        content.push_str("import { z } from 'zod';\n\n");

        // Collect all types used by commands
        let mut used_types = HashSet::new();
        for command in commands {
            for param in &command.parameters {
                self.collect_referenced_types(&param.rust_type, &mut used_types);
            }
            self.collect_referenced_types(&command.return_type, &mut used_types);
        }

        // Add nested dependencies
        let mut all_types: HashSet<String> = used_types.clone();
        self.discover_nested_dependencies(&used_types, discovered_structs, &mut all_types);

        // Generate schemas for discovered structs in topological order
        let sorted_types = analyzer.topological_sort_types(&all_types);
        for type_name in &sorted_types {
            if let Some(struct_info) = discovered_structs.get(type_name) {
                if struct_info.is_enum {
                    content.push_str(&self.generate_enum_schema(struct_info));
                } else {
                    content.push_str(&self.generate_struct_schema(struct_info));
                }
                content.push_str("\n");
            }
        }

        // Generate parameter schemas for commands
        for command in commands {
            if !command.parameters.is_empty() {
                let schema = self.generate_params_schema(command);
                content.push_str(&schema);
                content.push_str("\n");
            }
        }

        Ok(content)
    }

    fn generate_types_file(
        &self,
        commands: &[CommandInfo],
        discovered_structs: &HashMap<String, StructInfo>,
        analyzer: &CommandAnalyzer,
    ) -> Result<String, Box<dyn std::error::Error>> {
        let mut content = String::new();

        content.push_str(&format!(
            "/**\n * Auto-generated TypeScript types for Tauri commands\n * Generated by tauri-plugin-typegen\n * Do not edit manually - regenerate using: cargo tauri-typegen generate\n */\n\n"
        ));

        content.push_str("import { z } from 'zod';\n\n");

        // Generate schemas first
        content.push_str(&self.generate_schemas_in_types_file(commands, discovered_structs, analyzer)?);
        
        // Then generate inferred types
        content.push_str(&self.generate_inferred_types(commands, discovered_structs)?);

        Ok(content)
    }

    fn generate_schemas_in_types_file(
        &self,
        commands: &[CommandInfo],
        discovered_structs: &HashMap<String, StructInfo>,
        analyzer: &CommandAnalyzer,
    ) -> Result<String, Box<dyn std::error::Error>> {
        let mut content = String::new();
        
        // Collect all types used by commands
        let mut used_types = HashSet::new();
        for command in commands {
            for param in &command.parameters {
                self.collect_referenced_types(&param.rust_type, &mut used_types);
            }
            self.collect_referenced_types(&command.return_type, &mut used_types);
        }

        // Add nested dependencies
        let mut all_types: HashSet<String> = used_types.clone();
        self.discover_nested_dependencies(&used_types, discovered_structs, &mut all_types);

        // Generate schemas for discovered structs in topological order
        let sorted_types = analyzer.topological_sort_types(&all_types);
        for type_name in &sorted_types {
            if let Some(struct_info) = discovered_structs.get(type_name) {
                if struct_info.is_enum {
                    content.push_str(&self.generate_enum_schema(struct_info));
                } else {
                    content.push_str(&self.generate_struct_schema(struct_info));
                }
                content.push_str("\n");
            }
        }

        // Generate parameter schemas for commands
        for command in commands {
            if !command.parameters.is_empty() {
                let schema = self.generate_params_schema(command);
                content.push_str(&schema);
                content.push_str("\n");
            }
        }

        Ok(content)
    }

    fn generate_inferred_types(
        &self,
        commands: &[CommandInfo],
        discovered_structs: &HashMap<String, StructInfo>,
    ) -> Result<String, Box<dyn std::error::Error>> {
        let mut content = String::new();
        
        // Collect all types used by commands
        let mut used_types = HashSet::new();
        for command in commands {
            for param in &command.parameters {
                self.collect_referenced_types(&param.rust_type, &mut used_types);
            }
            self.collect_referenced_types(&command.return_type, &mut used_types);
        }

        // Add nested dependencies
        let mut all_types: HashSet<String> = used_types.clone();
        self.discover_nested_dependencies(&used_types, discovered_structs, &mut all_types);

        // Generate inferred types from schemas
        for type_name in &all_types {
            if discovered_structs.contains_key(type_name) {
                content.push_str(&format!(
                    "export type {} = z.infer<typeof {}Schema>;\n\n",
                    type_name, type_name
                ));
            }
        }

        // Generate parameter types for commands
        for command in commands {
            if !command.parameters.is_empty() {
                let params_type_name = format!("{}Params", self.to_pascal_case(&command.name));
                content.push_str(&format!(
                    "export type {} = z.infer<typeof {}Schema>;\n\n",
                    params_type_name, params_type_name
                ));
            }
        }

        Ok(content)
    }

    fn generate_struct_schema(&self, struct_info: &StructInfo) -> String {
        let mut content = format!("export const {}Schema = z.object({{\n", struct_info.name);

        for field in &struct_info.fields {
            if field.is_public {
                let field_name = self.to_camel_case(&field.name);
                let mut zod_type = self.typescript_to_zod_type(&field.typescript_type);
                
                // Apply validator constraints if present
                if let Some(validator_attrs) = &field.validator_attributes {
                    zod_type = self.apply_validator_constraints(zod_type, validator_attrs);
                }
                
                let optional_suffix = if field.is_optional { ".optional()" } else { "" };
                content.push_str(&format!(
                    "  {}: {}{},\n",
                    field_name, zod_type, optional_suffix
                ));
            }
        }

        content.push_str("});\n");
        content
    }

    fn apply_validator_constraints(&self, mut zod_type: String, validator_attrs: &ValidatorAttributes) -> String {
        // Apply email validation
        if validator_attrs.email {
            if zod_type == "z.string()" {
                zod_type = "z.string().email()".to_string();
            }
        }
        
        // Apply URL validation
        if validator_attrs.url {
            if zod_type == "z.string()" {
                zod_type = "z.string().url()".to_string();
            }
        }
        
        // Apply length constraints
        if let Some(length_constraint) = &validator_attrs.length {
            if zod_type.starts_with("z.string()") {
                zod_type = self.apply_length_constraint_to_string(zod_type, length_constraint);
            } else if zod_type.starts_with("z.array(") {
                zod_type = self.apply_length_constraint_to_array(zod_type, length_constraint);
            }
        }
        
        // Apply range constraints  
        if let Some(range_constraint) = &validator_attrs.range {
            if zod_type == "z.number()" {
                zod_type = self.apply_range_constraint_to_number(zod_type, range_constraint);
            }
        }
        
        zod_type
    }

    fn apply_length_constraint_to_string(&self, zod_type: String, constraint: &LengthConstraint) -> String {
        let mut result = zod_type;
        
        if let Some(min) = constraint.min {
            result = format!("{}.min({})", result, min);
            if let Some(message) = &constraint.message {
                result = format!("{}.min({}, \"{}\")", result.trim_end_matches(&format!(".min({})", min)), min, message);
            }
        }
        
        if let Some(max) = constraint.max {
            result = format!("{}.max({})", result, max);
            if let Some(message) = &constraint.message {
                result = format!("{}.max({}, \"{}\")", result.trim_end_matches(&format!(".max({})", max)), max, message);
            }
        }
        
        result
    }

    fn apply_length_constraint_to_array(&self, zod_type: String, constraint: &LengthConstraint) -> String {
        let mut result = zod_type;
        
        if let Some(min) = constraint.min {
            result = format!("{}.min({})", result, min);
        }
        
        if let Some(max) = constraint.max {
            result = format!("{}.max({})", result, max);
        }
        
        result
    }

    fn apply_range_constraint_to_number(&self, zod_type: String, constraint: &RangeConstraint) -> String {
        let mut result = zod_type;
        
        if let Some(min) = constraint.min {
            result = format!("{}.min({})", result, min);
        }
        
        if let Some(max) = constraint.max {
            result = format!("{}.max({})", result, max);
        }
        
        result
    }

    fn generate_enum_schema(&self, struct_info: &StructInfo) -> String {
        let variants: Vec<String> = struct_info
            .fields
            .iter()
            .map(|field| format!("\"{}\"", field.name))
            .collect();

        if variants.is_empty() {
            format!("export const {}Schema = z.never();\n", struct_info.name)
        } else {
            format!(
                "export const {}Schema = z.enum([{}]);\n",
                struct_info.name,
                variants.join(", ")
            )
        }
    }

    fn generate_params_schema(&self, command: &CommandInfo) -> String {
        let schema_name = format!("{}ParamsSchema", self.to_pascal_case(&command.name));
        let mut content = format!("export const {} = z.object({{\n", schema_name);

        for param in &command.parameters {
            let param_name = self.to_camel_case(&param.name);
            let zod_type = self.typescript_to_zod_type(&param.typescript_type);
            let optional_suffix = if param.is_optional { ".optional()" } else { "" };
            content.push_str(&format!(
                "  {}: {}{},\n",
                param_name, zod_type, optional_suffix
            ));
        }

        content.push_str("});\n");
        content
    }

    fn generate_command_bindings(
        &self,
        commands: &[CommandInfo],
    ) -> Result<String, Box<dyn std::error::Error>> {
        let mut content = String::new();

        content.push_str(&format!(
            "/**\n * Auto-generated command bindings for Tauri commands\n * Generated by tauri-plugin-typegen\n * Do not edit manually - regenerate using: cargo tauri-typegen generate\n */\n\n"
        ));

        content.push_str("import { invoke } from '@tauri-apps/api/core';\n");
        content.push_str("import * as types from './types';\n\n");

        for command in commands {
            let binding = self.generate_command_binding(command);
            content.push_str(&binding);
            content.push_str("\n");
        }

        Ok(content)
    }

    fn generate_command_binding(&self, command: &CommandInfo) -> String {
        let function_name = self.to_camel_case(&command.name);
        let return_type = self.format_return_type(&command.return_type);

        let mut content = String::new();

        if command.parameters.is_empty() {
            // No parameters
            content.push_str(&format!(
                "export async function {}(): Promise<{}> {{\n  return invoke('{}');\n}}\n",
                function_name, return_type, command.name
            ));
        } else {
            // Has parameters
            let params_type = format!("types.{}Params", self.to_pascal_case(&command.name));
            let schema_name = format!("types.{}ParamsSchema", self.to_pascal_case(&command.name));

            content.push_str(&format!(
                "export async function {}(params: {}): Promise<{}> {{\n",
                function_name, params_type, return_type
            ));

            content.push_str(&format!(
                "  const validatedParams = {}.parse(params);\n  return invoke('{}', validatedParams);\n",
                schema_name,
                command.name
            ));

            content.push_str("}\n");
        }

        content
    }

    fn format_return_type(&self, return_type: &str) -> String {
        // If it's a primitive type, return as-is
        if matches!(
            return_type,
            "string" | "number" | "boolean" | "void" | "any" | "unknown" | "null" | "undefined"
        ) {
            return return_type.to_string();
        }
        
        // If it ends with [] (array), handle the inner type
        if return_type.ends_with("[]") {
            let inner_type = &return_type[..return_type.len() - 2];
            let formatted_inner = self.format_return_type(inner_type);
            return format!("{}[]", formatted_inner);
        }
        
        // If it contains | (union type), handle each part
        if return_type.contains(" | ") {
            let parts: Vec<String> = return_type
                .split(" | ")
                .map(|part| self.format_return_type(part.trim()))
                .collect();
            return parts.join(" | ");
        }
        
        // Otherwise, it's a custom type - prefix with types.
        format!("types.{}", return_type)
    }

    fn generate_index_file(
        &self,
        generated_files: &[String],
    ) -> Result<String, Box<dyn std::error::Error>> {
        let mut content = String::new();

        content.push_str(&format!(
            "/**\n * Auto-generated TypeScript bindings for Tauri commands\n * Generated by tauri-plugin-typegen\n * Do not edit manually - regenerate using: cargo tauri-typegen generate\n */\n\n"
        ));

        for file in generated_files {
            if file != "index.ts" {
                let module_name = file.strip_suffix(".ts").unwrap_or(file);
                content.push_str(&format!("export * from './{}';\n", module_name));
            }
        }

        Ok(content)
    }

    // Helper method to recursively collect referenced types
    pub fn collect_referenced_types(&self, rust_type: &str, used_types: &mut HashSet<String>) {
        let rust_type = rust_type.trim();
        
        // Handle Result<T, E> - extract both T and E
        if rust_type.starts_with("Result<") {
            if let Some(inner) = rust_type
                .strip_prefix("Result<")
                .and_then(|s| s.strip_suffix(">"))
            {
                if let Some(comma_pos) = inner.find(',') {
                    let ok_type = inner[..comma_pos].trim();
                    let err_type = inner[comma_pos + 1..].trim();
                    self.collect_referenced_types(ok_type, used_types);
                    self.collect_referenced_types(err_type, used_types);
                }
            }
            return;
        }

        // Handle Option<T> - extract T
        if rust_type.starts_with("Option<") {
            if let Some(inner) = rust_type
                .strip_prefix("Option<")
                .and_then(|s| s.strip_suffix(">"))
            {
                self.collect_referenced_types(inner.trim(), used_types);
            }
            return;
        }

        // Handle Vec<T> - extract T
        if rust_type.starts_with("Vec<") {
            if let Some(inner) = rust_type
                .strip_prefix("Vec<")
                .and_then(|s| s.strip_suffix(">"))
            {
                self.collect_referenced_types(inner.trim(), used_types);
            }
            return;
        }
        
        // Handle HashMap<K, V> and BTreeMap<K, V> - extract K and V
        if rust_type.starts_with("HashMap<") || rust_type.starts_with("BTreeMap<") {
            let prefix = if rust_type.starts_with("HashMap<") { "HashMap<" } else { "BTreeMap<" };
            if let Some(inner) = rust_type
                .strip_prefix(prefix)
                .and_then(|s| s.strip_suffix(">"))
            {
                if let Some(comma_pos) = inner.find(',') {
                    let key_type = inner[..comma_pos].trim();
                    let value_type = inner[comma_pos + 1..].trim();
                    self.collect_referenced_types(key_type, used_types);
                    self.collect_referenced_types(value_type, used_types);
                }
            }
            return;
        }
        
        // Handle HashSet<T> and BTreeSet<T> - extract T
        if rust_type.starts_with("HashSet<") || rust_type.starts_with("BTreeSet<") {
            let prefix = if rust_type.starts_with("HashSet<") { "HashSet<" } else { "BTreeSet<" };
            if let Some(inner) = rust_type
                .strip_prefix(prefix)
                .and_then(|s| s.strip_suffix(">"))
            {
                self.collect_referenced_types(inner.trim(), used_types);
            }
            return;
        }
        
        // Handle tuple types like (T, U, V)
        if rust_type.starts_with('(') && rust_type.ends_with(')') && rust_type != "()" {
            let inner = &rust_type[1..rust_type.len()-1];
            for part in inner.split(',') {
                self.collect_referenced_types(part.trim(), used_types);
            }
            return;
        }

        // Handle references
        if rust_type.starts_with("&") {
            let without_ref = rust_type.trim_start_matches('&');
            self.collect_referenced_types(without_ref, used_types);
            return;
        }

        // Skip primitive types
        if matches!(
            rust_type,
            "String"
                | "str"
                | "i32"
                | "i64"
                | "f32"
                | "f64"
                | "bool"
                | "usize"
                | "isize"
                | "u32"
                | "u64"
                | "()"
                | "u8"
                | "i8"
                | "u16"
                | "i16"
                | "u128"
                | "i128"
        ) {
            return;
        }

        // This is a custom type - add it to the set
        if !rust_type.is_empty() && rust_type.chars().next().map_or(false, char::is_alphabetic) {
            used_types.insert(rust_type.to_string());
        }
    }

    fn discover_nested_dependencies(
        &self,
        initial_types: &HashSet<String>,
        discovered_structs: &HashMap<String, StructInfo>,
        all_types: &mut HashSet<String>
    ) {
        let mut to_process: Vec<String> = initial_types.iter().cloned().collect();
        let mut processed: HashSet<String> = HashSet::new();
        
        while let Some(type_name) = to_process.pop() {
            if processed.contains(&type_name) {
                continue;
            }
            processed.insert(type_name.clone());
            
            if let Some(struct_info) = discovered_structs.get(&type_name) {
                for field in &struct_info.fields {
                    let mut nested_types = HashSet::new();
                    self.collect_referenced_types(&field.typescript_type, &mut nested_types);
                    
                    for nested_type in nested_types {
                        if !all_types.contains(&nested_type) && discovered_structs.contains_key(&nested_type) {
                            all_types.insert(nested_type.clone());
                            to_process.push(nested_type);
                        }
                    }
                }
            }
        }
    }

    pub fn typescript_to_zod_type(&self, ts_type: &str) -> String {
        // Handle arrays first (before nullable check)
        if ts_type.ends_with("[]") {
            let item_type = &ts_type[..ts_type.len() - 2];
            // Remove parentheses if they exist around the item type
            let item_type = if item_type.starts_with('(') && item_type.ends_with(')') {
                &item_type[1..item_type.len()-1]
            } else {
                item_type
            };
            return format!("z.array({})", self.typescript_to_zod_type(item_type));
        }
        
        // Handle tuple types [T, U, V] - BEFORE nullable types
        if ts_type.starts_with('[') && ts_type.ends_with(']') {
            // Check if this is a nullable tuple (entire tuple is nullable)
            if ts_type.ends_with("] | null") {
                // This is handled by the nullable check below
            } else {
                // This is a regular tuple, possibly with nullable elements inside
                let inner = &ts_type[1..ts_type.len()-1];
                let types: Vec<String> = inner
                    .split(',')
                    .map(|part| self.typescript_to_zod_type(part.trim()))
                    .collect();
                return format!("z.tuple([{}])", types.join(", "));
            }
        }
        
        // Handle nullable types
        if ts_type.contains(" | null") {
            let base_type = ts_type.replace(" | null", "");
            return format!("{}.nullable()", self.typescript_to_zod_type(&base_type));
        }
        
        // Handle Record<K, V> types (from HashMap/BTreeMap)
        if ts_type.starts_with("Record<") {
            if let Some(inner) = ts_type.strip_prefix("Record<").and_then(|s| s.strip_suffix(">")) {
                if let Some(comma_pos) = inner.find(',') {
                    let key_type = inner[..comma_pos].trim();
                    let value_type = inner[comma_pos + 1..].trim();
                    let key_schema = self.typescript_to_zod_type(key_type);
                    let value_schema = self.typescript_to_zod_type(value_type);
                    return format!("z.record({}, {})", key_schema, value_schema);
                }
            }
            return "z.record(z.string(), z.any())".to_string();
        }

        match ts_type {
            "string" => "z.string()".to_string(),
            "number" => "z.number()".to_string(),
            "boolean" => "z.boolean()".to_string(),
            "void" => "z.void()".to_string(),
            _ => {
                // For custom types, reference them from schemas module
                if self.known_structs.contains_key(ts_type) {
                    format!("{}Schema", ts_type)
                } else {
                    // Unknown custom type - use a lazy reference or any
                    format!("z.lazy(() => z.any()) /* {} - define schema separately if needed */", ts_type)
                }
            }
        }
    }

    pub fn to_pascal_case(&self, s: &str) -> String {
        s.split('_')
            .map(|word| {
                let mut chars = word.chars();
                match chars.next() {
                    None => String::new(),
                    Some(first) => first.to_uppercase().chain(chars).collect(),
                }
            })
            .collect()
    }

    pub fn to_camel_case(&self, s: &str) -> String {
        let pascal = self.to_pascal_case(s);
        let mut chars = pascal.chars();
        match chars.next() {
            None => String::new(),
            Some(first) => first.to_lowercase().chain(chars).collect(),
        }
    }

    pub fn is_custom_type(&self, ts_type: &str) -> bool {
        !matches!(
            ts_type,
            "string" | "number" | "boolean" | "void" | "any" | "unknown" | "null" | "undefined"
        ) && !ts_type.ends_with("[]")
            && !ts_type.contains(" | ")
    }
}