name: Bug Report
description: Report a bug or unexpected behavior
labels: [bug]
body:
  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Which module does this relate to?
      options:
        - ts (vanilla TypeScript generation)
        - zod (Zod schema generation)
        - common (shared/core functionality)
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Which version of tauri-typegen are you using?
      options:
        - 0.3.4
        - 0.3.3
        - 0.3.2
        - 0.3.1
        - 0.3.0
        - 0.2.1
        - 0.2.0
        - 0.1.6
        - 0.1.5
        - 0.1.4
        - 0.1.3
        - 0.1.2
        - 0.1.1
        - 0.1.0
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      placeholder: |
        OS: macOS 14.0 / Windows 11 / Ubuntu 22.04
        Rust: 1.77.0
        Tauri: 2.0.0
      render: markdown
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Provide your plugin config (tauri.conf.json typegen section) or CLI parameters used
      placeholder: |
        CLI: cargo tauri-typegen generate --validation zod --verbose

        Or config:
        {
          "typegen": {
            "validation": "zod",
            ...
          }
        }
      render: json
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Provide relevant Rust code or generated TypeScript that demonstrates the issue
      placeholder: |
        ```rust
        #[tauri::command]
        fn my_command() -> Result<String, String> {
            // ...
        }
        ```

        ```typescript
        function myCommand() {
            // ...
        }
        ```
      render: markdown
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a detailed description of the bug
      placeholder: Describe the bug you encountered, including expected vs actual behavior...
    validations:
      required: true
