name: Feature Request
description: Suggest a new feature or enhancement
labels: [enhancement]
body:
  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Which module does this relate to?
      options:
        - ts (vanilla TypeScript generation)
        - zod (Zod schema generation)
        - common (shared/core functionality)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a detailed description of the feature you'd like to see
      placeholder: Describe the feature, its use case, and any implementation ideas...
    validations:
      required: true
