/**
 * Auto-generated command bindings for Tauri commands
 * Generated by tauri-plugin-typegen
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

import { invoke } from '@tauri-apps/api/core';

import * as types from './types';

export async function getBodyData(): Promise<types.BodyData> {
  return invoke('get_body_data');
}

export async function updateBodyData(params: types.UpdateBodyDataParams): Promise<types.BodyData> {
  const validatedParams = types.UpdateBodyDataParamsSchema.parse(params);
  return invoke('update_body_data', validatedParams);
}

export async function wizardCalculateTdee(params: types.WizardCalculateTdeeParams): Promise<types.WizardResult> {
  const validatedParams = types.WizardCalculateTdeeParamsSchema.parse(params);
  return invoke('wizard_calculate_tdee', validatedParams);
}

export async function wizardCreateTargets(params: types.WizardCreateTargetsParams): Promise<void> {
  const validatedParams = types.WizardCreateTargetsParamsSchema.parse(params);
  return invoke('wizard_create_targets', validatedParams);
}

export async function wizardCalculateForTargetDate(params: types.WizardCalculateForTargetDateParams): Promise<types.WizardTargetDateResult> {
  const validatedParams = types.WizardCalculateForTargetDateParamsSchema.parse(params);
  return invoke('wizard_calculate_for_target_date', validatedParams);
}

export async function wizardCalculateForTargetWeight(params: types.WizardCalculateForTargetWeightParams): Promise<types.WizardTargetWeightResult> {
  const validatedParams = types.WizardCalculateForTargetWeightParamsSchema.parse(params);
  return invoke('wizard_calculate_for_target_weight', validatedParams);
}

export async function createCalorieTarget(params: types.CreateCalorieTargetParams): Promise<types.CalorieTarget> {
  const validatedParams = types.CreateCalorieTargetParamsSchema.parse(params);
  return invoke('create_calorie_target', validatedParams);
}

export async function getLastCalorieTarget(): Promise<types.CalorieTarget> {
  return invoke('get_last_calorie_target');
}

export async function createCalorieTrackerEntry(params: types.CreateCalorieTrackerEntryParams): Promise<types.CalorieTracker> {
  const validatedParams = types.CreateCalorieTrackerEntryParamsSchema.parse(params);
  return invoke('create_calorie_tracker_entry', validatedParams);
}

export async function updateCalorieTrackerEntry(params: types.UpdateCalorieTrackerEntryParams): Promise<types.CalorieTracker> {
  const validatedParams = types.UpdateCalorieTrackerEntryParamsSchema.parse(params);
  return invoke('update_calorie_tracker_entry', validatedParams);
}

export async function deleteCalorieTrackerEntry(params: types.DeleteCalorieTrackerEntryParams): Promise<number> {
  const validatedParams = types.DeleteCalorieTrackerEntryParamsSchema.parse(params);
  return invoke('delete_calorie_tracker_entry', validatedParams);
}

export async function getCalorieTrackerForDateRange(params: types.GetCalorieTrackerForDateRangeParams): Promise<types.CalorieTracker[]> {
  const validatedParams = types.GetCalorieTrackerForDateRangeParamsSchema.parse(params);
  return invoke('get_calorie_tracker_for_date_range', validatedParams);
}

export async function getCalorieTrackerDatesInRange(params: types.GetCalorieTrackerDatesInRangeParams): Promise<string[]> {
  const validatedParams = types.GetCalorieTrackerDatesInRangeParamsSchema.parse(params);
  return invoke('get_calorie_tracker_dates_in_range', validatedParams);
}

export async function createWeightTarget(params: types.CreateWeightTargetParams): Promise<types.WeightTarget> {
  const validatedParams = types.CreateWeightTargetParamsSchema.parse(params);
  return invoke('create_weight_target', validatedParams);
}

export async function getWeightTargets(): Promise<types.WeightTarget[]> {
  return invoke('get_weight_targets');
}

export async function getLastWeightTarget(): Promise<types.WeightTarget> {
  return invoke('get_last_weight_target');
}

export async function updateWeightTarget(params: types.UpdateWeightTargetParams): Promise<types.WeightTarget> {
  const validatedParams = types.UpdateWeightTargetParamsSchema.parse(params);
  return invoke('update_weight_target', validatedParams);
}

export async function deleteWeightTarget(params: types.DeleteWeightTargetParams): Promise<number> {
  const validatedParams = types.DeleteWeightTargetParamsSchema.parse(params);
  return invoke('delete_weight_target', validatedParams);
}

export async function createWeightTrackerEntry(params: types.CreateWeightTrackerEntryParams): Promise<types.WeightTracker> {
  const validatedParams = types.CreateWeightTrackerEntryParamsSchema.parse(params);
  return invoke('create_weight_tracker_entry', validatedParams);
}

export async function updateWeightTrackerEntry(params: types.UpdateWeightTrackerEntryParams): Promise<types.WeightTracker> {
  const validatedParams = types.UpdateWeightTrackerEntryParamsSchema.parse(params);
  return invoke('update_weight_tracker_entry', validatedParams);
}

export async function deleteWeightTrackerEntry(params: types.DeleteWeightTrackerEntryParams): Promise<number> {
  const validatedParams = types.DeleteWeightTrackerEntryParamsSchema.parse(params);
  return invoke('delete_weight_tracker_entry', validatedParams);
}

export async function getWeightTrackerForDateRange(params: types.GetWeightTrackerForDateRangeParams): Promise<types.WeightTracker[]> {
  const validatedParams = types.GetWeightTrackerForDateRangeParamsSchema.parse(params);
  return invoke('get_weight_tracker_for_date_range', validatedParams);
}

export async function getTrackerProgress(params: types.GetTrackerProgressParams): Promise<types.Progress> {
  const validatedParams = types.GetTrackerProgressParamsSchema.parse(params);
  return invoke('get_tracker_progress', validatedParams);
}

export async function updateUser(params: types.UpdateUserParams): Promise<types.LibreUser> {
  const validatedParams = types.UpdateUserParamsSchema.parse(params);
  return invoke('update_user', validatedParams);
}

export async function getUser(): Promise<types.LibreUser | null> {
  return invoke('get_user');
}

export async function getTrackerHistory(params: types.GetTrackerHistoryParams): Promise<types.TrackerHistory> {
  const validatedParams = types.GetTrackerHistoryParamsSchema.parse(params);
  return invoke('get_tracker_history', validatedParams);
}

export async function getFoodCategories(): Promise<types.FoodCategory[]> {
  return invoke('get_food_categories');
}

export async function getFoodCategory(params: types.GetFoodCategoryParams): Promise<types.FoodCategory> {
  const validatedParams = types.GetFoodCategoryParamsSchema.parse(params);
  return invoke('get_food_category', validatedParams);
}

export async function dailyDashboard(params: types.DailyDashboardParams): Promise<types.Dashboard> {
  const validatedParams = types.DailyDashboardParamsSchema.parse(params);
  return invoke('daily_dashboard', validatedParams);
}

