/**
 * Auto-generated TypeScript types for Tauri commands
 * Generated by tauri-plugin-typegen
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

import { z } from 'zod';

export const CalculationGoalSchema = z.enum(["GAIN", "LOSS"]);

export const BmiCategorySchema = z.enum(["Underweight", "StandardWeight", "Overweight", "Obese", "SeverelyObese"]);

export const CalculationSexSchema = z.enum(["MALE", "FEMALE"]);

export const WizardInputSchema = z.object({
  age: z.number().min(18).max(99),
  sex: CalculationSexSchema,
  weight: z.number().min(30).max(300),
  height: z.number().min(100).max(220),
  activityLevel: z.number(),
  weeklyDifference: z.number().min(0).max(7),
  calculationGoal: CalculationGoalSchema,
});

export const NewWeightTrackerSchema = z.object({
  added: z.string(),
  amount: z.number().min(30, { message: "Weight must be between 30 and 330 kg" }).max(330, { message: "Weight must be between 30 and 330 kg" }),
});

export const WeightTargetSchema = z.object({
  id: z.number(),
  added: z.string(),
  endDate: z.string(),
  initialWeight: z.number(),
  startDate: z.string(),
  targetWeight: z.number(),
});

export const WizardRecommendationSchema = z.enum(["HOLD", "LOSE", "GAIN"]);

export const WeightTrackerSchema = z.object({
  id: z.number(),
  added: z.string(),
  amount: z.number().min(30, { message: "Weight must be between 30 and 330 kg" }).max(330, { message: "Weight must be between 30 and 330 kg" }),
});

export const WizardTargetDateResultSchema = z.object({
  weightByRate: z.record(z.number(), z.number()),
  bmiByRate: z.record(z.number(), z.number()),
});

export const WizardTargetDateInputSchema = z.object({
  age: z.number().min(18).max(99),
  sex: CalculationSexSchema,
  currentWeight: z.number().min(30).max(300),
  height: z.number().min(100).max(220),
  calculationGoal: CalculationGoalSchema,
  targetDate: z.string(),
  startDate: z.string(),
});

export const WizardTargetWeightInputSchema = z.object({
  age: z.number().min(18).max(99),
  sex: CalculationSexSchema,
  currentWeight: z.number().min(30).max(300),
  height: z.number().min(100).max(220),
  targetWeight: z.number().min(30).max(300),
  startDate: z.string(),
});

export const CalorieChartDataSchema = z.object({
  avg: z.number(),
  min: z.number(),
  max: z.number(),
  legend: z.array(z.string()),
  values: z.array(z.number()),
  categoryAverage: z.record(z.string(), z.number()),
  dailyAverage: z.number(),
});

export const NewCalorieTargetSchema = z.object({
  added: z.string(),
  endDate: z.string(),
  maximumCalories: z.number().min(1, { message: "Maximum calories must be between 1 and 10,000" }).max(10000, { message: "Maximum calories must be between 1 and 10,000" }),
  startDate: z.string(),
  targetCalories: z.number().min(1, { message: "Target calories must be between 1 and 10,000" }).max(10000, { message: "Target calories must be between 1 and 10,000" }),
});

export const NewWeightTargetSchema = z.object({
  added: z.string(),
  endDate: z.string(),
  initialWeight: z.number().min(30, { message: "Initial weight must be between 30 and 300 kg" }).max(300, { message: "Initial weight must be between 30 and 300 kg" }),
  startDate: z.string(),
  targetWeight: z.number().min(30, { message: "Target weight must be between 30 and 300 kg" }).max(300, { message: "Target weight must be between 30 and 300 kg" }),
});

export const WeightChartDataSchema = z.object({
  avg: z.number(),
  min: z.number(),
  max: z.number(),
  legend: z.array(z.string()),
  values: z.array(z.number()),
});

export const CalorieTargetSchema = z.object({
  id: z.number(),
  added: z.string(),
  endDate: z.string(),
  maximumCalories: z.number(),
  startDate: z.string(),
  targetCalories: z.number(),
});

export const ProgressSchema = z.object({
  calorieTarget: CalorieTargetSchema,
  weightTarget: WeightTargetSchema,
  daysPassed: z.number(),
  daysTotal: z.number(),
  calorieChartData: CalorieChartDataSchema,
  weightChartData: WeightChartDataSchema,
});

export const CalorieTrackerSchema = z.object({
  id: z.number(),
  added: z.string(),
  amount: z.number().min(1, { message: "Calorie amount must be between 1 and 10,000" }).max(10000, { message: "Calorie amount must be between 1 and 10,000" }),
  category: z.string().min(1, { message: "Category must be between 1 and 50 characters" }).max(50, { message: "Category must be between 1 and 50 characters" }),
  description: z.string().max(500, { message: "Description must be less than 500 characters" }).optional(),
});

export const TrackerHistorySchema = z.object({
  caloriesHistory: z.record(z.string(), z.array(CalorieTrackerSchema)),
  caloriesAverage: z.number(),
  weightHistory: z.record(z.string(), z.array(WeightTrackerSchema)),
  dateLastStr: z.string(),
});

export const BodyDataSchema = z.object({
  id: z.number(),
  age: z.number().min(18, { message: "Age must be between 18 and 99 years." }).max(99, { message: "Age must be between 18 and 99 years." }),
  height: z.number().min(100, { message: "Height must be between 100 and 220cm." }).max(220, { message: "Height must be between 100 and 220cm." }),
  weight: z.number().min(30, { message: "Weight must be btween 30 and 330kg." }).max(330, { message: "Weight must be btween 30 and 330kg." }),
  sex: z.string(),
});

export const WizardSchema = z.object({
  calorieTarget: NewCalorieTargetSchema,
  weightTarget: NewWeightTargetSchema,
  weightTracker: NewWeightTrackerSchema,
});

export const LibreUserSchema = z.object({
  id: z.number(),
  avatar: z.string().optional(),
  name: z.string().optional(),
});

export const FoodCategorySchema = z.object({
  longvalue: z.string(),
  shortvalue: z.string(),
});

export const WizardTargetWeightResultSchema = z.object({
  dateByRate: z.record(z.number(), z.string()),
  progressByRate: z.record(z.number(), z.number()),
  targetClassification: BmiCategorySchema,
  warning: z.boolean(),
  message: z.string(),
});

export const DashboardSchema = z.object({
  userData: LibreUserSchema.optional(),
  calorieTarget: CalorieTargetSchema,
  caloriesTodayList: z.array(CalorieTrackerSchema),
  caloriesWeekList: z.array(CalorieTrackerSchema),
  weightTarget: WeightTargetSchema,
  weightTodayList: z.array(WeightTrackerSchema),
  weightMonthList: z.array(WeightTrackerSchema),
  foodCategories: z.array(FoodCategorySchema),
  currentDay: z.number(),
});

export const WizardResultSchema = z.object({
  bmr: z.number(),
  tdee: z.number(),
  deficit: z.number(),
  target: z.number(),
  bmi: z.number(),
  bmiCategory: BmiCategorySchema,
  recommendation: WizardRecommendationSchema,
  targetBmi: z.number(),
  targetBmiUpper: z.number(),
  targetBmiLower: z.number(),
  targetWeight: z.number(),
  targetWeightUpper: z.number(),
  targetWeightLower: z.number(),
  durationDays: z.number(),
  durationDaysUpper: z.number(),
  durationDaysLower: z.number(),
});

export const NewCalorieTrackerSchema = z.object({
  added: z.string(),
  amount: z.number().min(1, { message: "Calorie amount must be between 1 and 10,000" }).max(10000, { message: "Calorie amount must be between 1 and 10,000" }),
  category: z.string().min(1, { message: "Category must be between 1 and 50 characters" }).max(50, { message: "Category must be between 1 and 50 characters" }),
  description: z.string().max(500, { message: "Description must be less than 500 characters" }).optional(),
});

export const UpdateBodyDataParamsSchema = z.object({
  age: z.number(),
  height: z.number(),
  weight: z.number(),
  sex: z.string(),
});

export const WizardCalculateTdeeParamsSchema = z.object({
  input: WizardInputSchema,
});

export const WizardCreateTargetsParamsSchema = z.object({
  input: WizardSchema,
});

export const WizardCalculateForTargetDateParamsSchema = z.object({
  input: WizardTargetDateInputSchema,
});

export const WizardCalculateForTargetWeightParamsSchema = z.object({
  input: WizardTargetWeightInputSchema,
});

export const CreateCalorieTargetParamsSchema = z.object({
  newTarget: NewCalorieTargetSchema,
});

export const CreateCalorieTrackerEntryParamsSchema = z.object({
  newEntry: NewCalorieTrackerSchema,
});

export const UpdateCalorieTrackerEntryParamsSchema = z.object({
  trackerId: z.number(),
  updatedEntry: NewCalorieTrackerSchema,
});

export const DeleteCalorieTrackerEntryParamsSchema = z.object({
  trackerId: z.number(),
});

export const GetCalorieTrackerForDateRangeParamsSchema = z.object({
  dateFromStr: z.string(),
  dateToStr: z.string(),
});

export const GetCalorieTrackerDatesInRangeParamsSchema = z.object({
  dateFromStr: z.string(),
  dateToStr: z.string(),
});

export const CreateWeightTargetParamsSchema = z.object({
  newTarget: NewWeightTargetSchema,
});

export const UpdateWeightTargetParamsSchema = z.object({
  targetId: z.number(),
  updatedTarget: NewWeightTargetSchema,
});

export const DeleteWeightTargetParamsSchema = z.object({
  targetId: z.number(),
});

export const CreateWeightTrackerEntryParamsSchema = z.object({
  newEntry: NewWeightTrackerSchema,
});

export const UpdateWeightTrackerEntryParamsSchema = z.object({
  trackerId: z.number(),
  updatedEntry: NewWeightTrackerSchema,
});

export const DeleteWeightTrackerEntryParamsSchema = z.object({
  trackerId: z.number(),
});

export const GetWeightTrackerForDateRangeParamsSchema = z.object({
  dateFromStr: z.string(),
  dateToStr: z.string(),
});

export const GetTrackerProgressParamsSchema = z.object({
  dateStr: z.string(),
});

export const UpdateUserParamsSchema = z.object({
  userName: z.string(),
  userAvatar: z.string(),
});

export const GetTrackerHistoryParamsSchema = z.object({
  dateFromStr: z.string(),
  dateToStr: z.string(),
});

export const GetFoodCategoryParamsSchema = z.object({
  shortvalue: z.string(),
});

export const DailyDashboardParamsSchema = z.object({
  dateStr: z.string(),
});

export type UpdateBodyDataParams = z.infer<typeof UpdateBodyDataParamsSchema>;

export type WizardCalculateTdeeParams = z.infer<typeof WizardCalculateTdeeParamsSchema>;

export type WizardCreateTargetsParams = z.infer<typeof WizardCreateTargetsParamsSchema>;

export type WizardCalculateForTargetDateParams = z.infer<typeof WizardCalculateForTargetDateParamsSchema>;

export type WizardCalculateForTargetWeightParams = z.infer<typeof WizardCalculateForTargetWeightParamsSchema>;

export type CreateCalorieTargetParams = z.infer<typeof CreateCalorieTargetParamsSchema>;

export type CreateCalorieTrackerEntryParams = z.infer<typeof CreateCalorieTrackerEntryParamsSchema>;

export type UpdateCalorieTrackerEntryParams = z.infer<typeof UpdateCalorieTrackerEntryParamsSchema>;

export type DeleteCalorieTrackerEntryParams = z.infer<typeof DeleteCalorieTrackerEntryParamsSchema>;

export type GetCalorieTrackerForDateRangeParams = z.infer<typeof GetCalorieTrackerForDateRangeParamsSchema>;

export type GetCalorieTrackerDatesInRangeParams = z.infer<typeof GetCalorieTrackerDatesInRangeParamsSchema>;

export type CreateWeightTargetParams = z.infer<typeof CreateWeightTargetParamsSchema>;

export type UpdateWeightTargetParams = z.infer<typeof UpdateWeightTargetParamsSchema>;

export type DeleteWeightTargetParams = z.infer<typeof DeleteWeightTargetParamsSchema>;

export type CreateWeightTrackerEntryParams = z.infer<typeof CreateWeightTrackerEntryParamsSchema>;

export type UpdateWeightTrackerEntryParams = z.infer<typeof UpdateWeightTrackerEntryParamsSchema>;

export type DeleteWeightTrackerEntryParams = z.infer<typeof DeleteWeightTrackerEntryParamsSchema>;

export type GetWeightTrackerForDateRangeParams = z.infer<typeof GetWeightTrackerForDateRangeParamsSchema>;

export type GetTrackerProgressParams = z.infer<typeof GetTrackerProgressParamsSchema>;

export type UpdateUserParams = z.infer<typeof UpdateUserParamsSchema>;

export type GetTrackerHistoryParams = z.infer<typeof GetTrackerHistoryParamsSchema>;

export type GetFoodCategoryParams = z.infer<typeof GetFoodCategoryParamsSchema>;

export type DailyDashboardParams = z.infer<typeof DailyDashboardParamsSchema>;

export type Wizard = z.infer<typeof WizardSchema>;

export type LibreUser = z.infer<typeof LibreUserSchema>;

export type WeightChartData = z.infer<typeof WeightChartDataSchema>;

export type FoodCategory = z.infer<typeof FoodCategorySchema>;

export type WizardInput = z.infer<typeof WizardInputSchema>;

export type WeightTarget = z.infer<typeof WeightTargetSchema>;

export type NewWeightTarget = z.infer<typeof NewWeightTargetSchema>;

export type WizardTargetDateResult = z.infer<typeof WizardTargetDateResultSchema>;

export type WizardTargetDateInput = z.infer<typeof WizardTargetDateInputSchema>;

export type WizardTargetWeightInput = z.infer<typeof WizardTargetWeightInputSchema>;

export type Dashboard = z.infer<typeof DashboardSchema>;

export type CalculationGoal = z.infer<typeof CalculationGoalSchema>;

export type TrackerHistory = z.infer<typeof TrackerHistorySchema>;

export type CalorieTarget = z.infer<typeof CalorieTargetSchema>;

export type CalorieTracker = z.infer<typeof CalorieTrackerSchema>;

export type Progress = z.infer<typeof ProgressSchema>;

export type CalorieChartData = z.infer<typeof CalorieChartDataSchema>;

export type NewCalorieTarget = z.infer<typeof NewCalorieTargetSchema>;

export type WizardTargetWeightResult = z.infer<typeof WizardTargetWeightResultSchema>;

export type NewWeightTracker = z.infer<typeof NewWeightTrackerSchema>;

export type CalculationSex = z.infer<typeof CalculationSexSchema>;

export type WizardRecommendation = z.infer<typeof WizardRecommendationSchema>;

export type BodyData = z.infer<typeof BodyDataSchema>;

export type WeightTracker = z.infer<typeof WeightTrackerSchema>;

export type WizardResult = z.infer<typeof WizardResultSchema>;

export type BmiCategory = z.infer<typeof BmiCategorySchema>;

export type NewCalorieTracker = z.infer<typeof NewCalorieTrackerSchema>;

